
project_id = "utuguowpwezberrmqabw"

[functions_permissions."execute_sql"]
verify_jwt = true

[functions_permissions."razorpay-payment"]
verify_jwt = true

[functions_permissions."secure-operations"]
verify_jwt = true

[functions_permissions."send-notification"]
verify_jwt = false

[functions_permissions."send-push-notification"]
verify_jwt = false

[functions_permissions."get_monthly_leaderboard"]
verify_jwt = true

[functions_permissions."pikwy-screenshot"]
verify_jwt = false

[functions_permissions."refresh-leaderboard"]
verify_jwt = false

[functions_permissions."process-extraction-jobs"]
verify_jwt = false

