// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utuguowpwezberrmqabw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0dWd1b3dwd2V6YmVycm1xYWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxNzEwODYsImV4cCI6MjA1NDc0NzA4Nn0.2ZEueLg2h5SQ-UiCMZPA2f7KZ-uLTFE_wLq0QDceTu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);